"use client";

import { useState, useRef, useEffect } from "react";
import { motion } from "motion/react";
import ReactMarkdown from "react-markdown";


export default function ChatPage() {
  const [loading, setLoading] = useState(false);
  const [input, setInput] = useState("");
  const [history, setHistory] = useState(
    [{
      role: "user",
      text: "You are a compassionate, non-judgmental AI therapist. Provide empathetic, evidence-based guidance, ask clarifying questions when needed, and keep answers brief, concise and safe.",
      timestamp: Date.now(),
    }]
  );

  // Reference hook to scroll to last message automatically
  const lastMessageRef = useRef(null);

  useEffect(() => {
    lastMessageRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [history]);


  async function sendMessage() {
    if (!input.trim()) return;

    // annotate the message
    const userMessage = {
      role: "user",
      text: input,
      timestamp: Date.now(),
    };

    // Update UI immediately
    setHistory((prev) => [...prev, userMessage]);
    setLoading(true);

    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        history,
        message: input,
      }),
    });

    const data = await res.json();
    setLoading(false);

    if (data.reply) {
      // annotate the reply
      const assistantMessage = {
        role: "assistant",
        text: data.reply,
        timestamp: Date.now(),
      };
      setHistory((prev) => [...prev, assistantMessage]);
    }

    setInput("");
  }

  return (
    <div className="relative max-w-2xl h-[70vh] border-[#7ADAA5] border rounded-2xl mx-auto mt-40 p-6 overflow-y-auto">

      {history.length == 1 ? (
        // Opening Message
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="h-[90%] flex flex-col gap-2 items-center justify-center">
          <div className="flex gap-2">
            <img src="/star.svg" alt="star" />
            <p className="text-4xl soft-green">AI Therapist</p>
          </div>
          <div>
            What's on your mind today?
          </div>
        </motion.div>

      ) : (
        // Chat Messages 
        <div className="h-[90%] overflow-y-auto">
          <div className="space-y-4 mx-4">
            {history.slice(1).map((msg) => (

              <div
                key={msg.timestamp}
                ref={msg === history[history.length - 1] ? lastMessageRef : null}
                className="flex gap-2 relative"
              >
                <div className={`p-4 rounded-2xl w-fit ${msg.role === "user"
                  ? "soft-blue-bg ml-auto"
                  : "soft-green-bg mr-auto"}`}
                >
                  {/* Formats raw markdown generated by AI*/}
                  <ReactMarkdown>
                    {msg.text}
                  </ReactMarkdown>
                </div>

                <div>
                  {msg.role === "user" ?
                    <img src="/user.svg" alt="user" className="justify-end" /> :
                    <img src="/robot.svg" alt="robot" className="justify-start" />
                  }
                </div>

              </div>
            )
            )}

            {loading && (
              <motion.div
                animate={{ opacity: [1, 0.5, 1] }}
                transition={{
                  duration: 1,
                  repeat: Infinity,
                  ease: "easeInOut",
                }}
                className="soft-green-bg p-3 rounded-lg w-fit">
                Thinking...
              </motion.div>
            )}
          </div>
        </div>
      )}


      {/* Input Box */}
      <div className="h-[10%]">
        <div className="p-5 flex justify-center items-center gap-2">
          <input
            className="flex-1 border-[#7ADAA5] border py-2 px-4 rounded-2xl"
            placeholder="Ask me anything..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && sendMessage()}
          />

          <button
            onClick={sendMessage}
            className="soft-green-bg text-white px-4 py-2 rounded-2xl cursor-pointer"
          >
            Send
          </button>
        </div>
      </div>

    </div>
  );
}
